services:
  - type: web
    name: code-review-app
    env: node
    plan: free
    buildCommand: npm install && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: NODE_ENV=production npm start
